// => models/shsCourseModel.js
// => Pure persistence layer for shs_courses + its job opportunities table.
// => Course-level lookups keyed by admin_uuid, the admin-dashboard-facing
// => identifier - never course_id. Cluster lookups moved to sectorClusterModel.js.

import { pool } from '../../config/db.js';
import { buildPartialUpdate } from '../../utils/buildPartialUpdate.js';

// => List view: excludes soft-deleted rows, joins cluster name for display
export async function findAllShsCourses() {
  const result = await pool.query(`
    SELECT sc.course_id, sc.admin_uuid, sc.title, sc.grade_level, sc.status, sc.cluster_id,
           cl.name AS cluster_name, sc.created_at
    FROM shs_courses sc
    LEFT JOIN shs_clusters cl ON cl.cluster_id = sc.cluster_id
    WHERE sc.deleted_at IS NULL
    ORDER BY sc.created_at DESC
  `);
  return result.rows;
}

export async function findShsCourseByAdminUuid(adminUuid) {
  const result = await pool.query(
    `SELECT sc.*, cl.name AS cluster_name
     FROM shs_courses sc
     LEFT JOIN shs_clusters cl ON cl.cluster_id = sc.cluster_id
     WHERE sc.admin_uuid = $1 AND sc.deleted_at IS NULL`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => admin_uuid is generated by the column DEFAULT - not set here.
// => Transactional (like tesdaCourseModel's insert) because it now also
// => inserts job opportunity rows in the same operation.
// => jobOpportunities = [{ job_title }]
export async function insertShsCourseWithJobOpportunities({ course, jobOpportunities, adminId }) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const courseResult = await client.query(
      `INSERT INTO shs_courses
        (cluster_id, title, description, cover_image_url, grade_level, course_link, status, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, 'active'), $8)
       RETURNING *`,
      [
        course.cluster_id,
        course.title,
        course.description ?? null,
        course.cover_image_url ?? null,
        course.grade_level,
        course.course_link ?? null,
        course.status ?? null,
        adminId ?? null,
      ]
    );

    const newCourse = courseResult.rows[0];

    for (const job of jobOpportunities || []) {
      if (!job.job_title) continue; // => skip incomplete rows silently
      await client.query(
        `INSERT INTO shs_job_opportunities (course_id, job_title) VALUES ($1, $2)`,
        [newCourse.course_id, job.job_title]
      );
    }

    await client.query('COMMIT');
    return newCourse;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

// => Whitelisted editable columns - admin_uuid intentionally excluded, same
// => reasoning as tesdaCourseModel.js
export const SHS_COURSE_ALLOWED_COLUMNS = new Set([
  'title', 'description', 'cover_image_url', 'cluster_id', 'grade_level', 'course_link', 'status',
]);

export async function updateShsCourse(adminUuid, fields) {
  const query = buildPartialUpdate({
    table: 'shs_courses',
    idColumn: 'admin_uuid',
    idValue: adminUuid,
    fields,
    allowedColumns: SHS_COURSE_ALLOWED_COLUMNS,
  });

  if (!query) return null;

  const result = await pool.query(query.text, query.values);
  return result.rows[0] || null;
}

// => Soft delete only - never hard delete a course
export async function softDeleteShsCourse(adminUuid) {
  const result = await pool.query(
    `UPDATE shs_courses
     SET deleted_at = NOW(), updated_at = NOW()
     WHERE admin_uuid = $1 AND deleted_at IS NULL
     RETURNING course_id, admin_uuid`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => Deleted-courses list - mirror of findAllShsCourses, flipped filter
export async function findAllDeletedShsCourses() {
  const result = await pool.query(`
    SELECT sc.course_id, sc.admin_uuid, sc.title, sc.grade_level, sc.status, sc.cluster_id,
           cl.name AS cluster_name, sc.deleted_at
    FROM shs_courses sc
    LEFT JOIN shs_clusters cl ON cl.cluster_id = sc.cluster_id
    WHERE sc.deleted_at IS NOT NULL
    ORDER BY sc.deleted_at DESC
  `);
  return result.rows;
}

// => Restore guard lookup: fetches a course's cluster_id regardless of its
// => own deleted_at status - findShsCourseByAdminUuid can't be reused here
// => since it filters out soft-deleted courses
export async function findShsCourseClusterIdForRestore(adminUuid) {
  const result = await pool.query(
    `SELECT course_id, cluster_id, title FROM shs_courses WHERE admin_uuid = $1`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => Un-deletes a course - clears deleted_at, nothing else
export async function restoreShsCourse(adminUuid) {
  const result = await pool.query(
    `UPDATE shs_courses
     SET deleted_at = NULL, updated_at = NOW()
     WHERE admin_uuid = $1 AND deleted_at IS NOT NULL
     RETURNING course_id, admin_uuid`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => Public link sub-resource removed (findPublicLinkByCourseId, isSlugTaken,
// => createPublicLink, updatePublicLink, PUBLIC_LINK_ALLOWED_COLUMNS) - the
// => publish gate was redundant with shs_courses.status, which is what the
// => public site actually filters on. shs_course_public_links table dropped in Neon.

// => Job opportunities sub-resource - same pattern as tesdaCourseModel.js

export async function findJobOpportunitiesByCourseId(courseId) {
  const result = await pool.query(
    `SELECT job_id AS id, job_title
     FROM shs_job_opportunities WHERE course_id = $1 ORDER BY job_id ASC`,
    [courseId]
  );
  return result.rows;
}

export async function insertSingleJobOpportunity(adminUuid, jobTitle) {
  const result = await pool.query(
    // => course_id added to RETURNING so the service layer can log the
    // => correct entity_id without a separate lookup query
    `INSERT INTO shs_job_opportunities (course_id, job_title)
     SELECT course_id, $2
     FROM shs_courses
     WHERE admin_uuid = $1 AND deleted_at IS NULL
     RETURNING course_id, job_id AS id, job_title`,
    [adminUuid, jobTitle]
  );
  return result.rows[0] || null;
}

export async function updateJobOpportunity(jobId, jobTitle) {
  const result = await pool.query(
    `UPDATE shs_job_opportunities SET job_title = $1 WHERE job_id = $2 RETURNING course_id, job_id AS id, job_title`,
    [jobTitle, jobId]
  );
  return result.rows[0] || null;
}

export async function deleteJobOpportunity(jobId) {
  const result = await pool.query(
    `DELETE FROM shs_job_opportunities WHERE job_id = $1 RETURNING course_id, job_id AS id`,
    [jobId]
  );
  return result.rows[0] || null;
}
