// => models/tesdaCourseModel.js
// => Pure persistence layer for tesda_courses + its 3 competency tables +
// => its job opportunities table. Sector lookups moved to sectorClusterModel.js.
// => Uses 'pool' exclusively (parameterized $1, $2... queries).
// => Course-level lookups (find/update/delete) are keyed by admin_uuid, the
// => admin-dashboard-facing identifier - never the raw internal course_id.
// => Competency/job-opportunity rows stay keyed by their own internal ids and
// => FK to the internal course_id - admin_uuid never touches those tables directly.
// => No validation here - that lives in tesdaCourseService.js.

import { pool } from '../../config/db.js';
import { buildPartialUpdate } from '../../utils/buildPartialUpdate.js';

// => List view: excludes soft-deleted rows, joins sector name for display
export async function findAllTesdaCourses() {
  const result = await pool.query(`
    SELECT tc.course_id, tc.admin_uuid, tc.title, tc.accreditation_no, tc.date_accredited,
           tc.expiration_date, tc.amount, tc.hours, tc.status, tc.sector_id,
           s.sector AS sector_name, tc.certification_id, nct.certification_type, tc.created_at
    FROM tesda_courses tc
    LEFT JOIN sectors s ON s.sector_id = tc.sector_id
    LEFT JOIN national_certification_types nct ON nct.certification_id = tc.certification_id
    WHERE tc.deleted_at IS NULL
    ORDER BY tc.created_at DESC
  `);
  return result.rows;
}

// => Full detail row for one course, looked up by admin_uuid
export async function findTesdaCourseByAdminUuid(adminUuid) {
  const result = await pool.query(
    `SELECT tc.*, s.sector AS sector_name, nct.certification_type
     FROM tesda_courses tc
     LEFT JOIN sectors s ON s.sector_id = tc.sector_id
     LEFT JOIN national_certification_types nct ON nct.certification_id = tc.certification_id
     WHERE tc.admin_uuid = $1 AND tc.deleted_at IS NULL`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => For the Create modal's and detail page's certification level dropdown -
// => read-only lookup, no "Add New" UI since TESDA only recognizes 4 fixed
// => levels (unlike sectors/clusters, which genuinely grow over time)
export async function findAllCertificationTypes() {
  const result = await pool.query(
    `SELECT certification_id, certification_type FROM national_certification_types ORDER BY certification_id ASC`
  );
  return result.rows;
}

// => Competency rows for one course - takes the INTERNAL course_id (already
// => resolved from admin_uuid by the service layer), since that's what these
// => tables actually FK against
export async function findCompetenciesByCourseId(courseId) {
  const basicResult = await pool.query(
    `SELECT basic_id AS id, code, competency
     FROM basic_competency WHERE course_id = $1 ORDER BY basic_id ASC`,
    [courseId]
  );
  const commonResult = await pool.query(
    `SELECT common_id AS id, code, competency
     FROM common_competency WHERE course_id = $1 ORDER BY common_id ASC`,
    [courseId]
  );
  const coreResult = await pool.query(
    `SELECT core_id AS id, code, competency
     FROM core_competency WHERE course_id = $1 ORDER BY core_id ASC`,
    [courseId]
  );
  return { basic: basicResult.rows, common: commonResult.rows, core: coreResult.rows };
}

// => Fixed, hardcoded map - table names are NEVER derived from request input,
// => only ever looked up by this literal whitelist keyed on 'basic'/'common'/'core'
const COMPETENCY_TABLES = {
  basic: { table: 'basic_competency', idColumn: 'basic_id' },
  common: { table: 'common_competency', idColumn: 'common_id' },
  core: { table: 'core_competency', idColumn: 'core_id' },
};

// => Creates a course + all its competency rows + job opportunity rows in a
// => single transaction via 'pool'. admin_uuid is generated by the column
// => DEFAULT - not set here.
// => competencies = { basic: [{code, competency}], common: [...], core: [...] }
// => jobOpportunities = [{ job_title }]
export async function insertTesdaCourseWithCompetencies({ course, competencies, jobOpportunities, adminId }) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const courseResult = await client.query(
      `INSERT INTO tesda_courses
        (title, description, accreditation_no, date_accredited, expiration_date,
         sector_id, certification_id, amount, hours, cover_image_url, status, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11, 'active'), $12)
       RETURNING *`,
      [
        course.title,
        course.description ?? null,
        course.accreditation_no,
        course.date_accredited,
        course.expiration_date,
        course.sector_id || null,
        course.certification_id || null,
        course.amount ?? 0,
        course.hours,
        course.cover_image_url ?? null,
        course.status ?? null,
        adminId ?? null,
      ]
    );

    const newCourse = courseResult.rows[0];

    for (const type of Object.keys(COMPETENCY_TABLES)) {
      const rows = competencies?.[type] || [];
      const { table } = COMPETENCY_TABLES[type];

      for (const row of rows) {
        if (!row.code || !row.competency) continue; // => skip incomplete rows silently
        await client.query(
          `INSERT INTO ${table} (course_id, code, competency) VALUES ($1, $2, $3)`,
          [newCourse.course_id, row.code, row.competency]
        );
      }
    }

    for (const job of jobOpportunities || []) {
      if (!job.job_title) continue; // => skip incomplete rows silently
      await client.query(
        `INSERT INTO tesda_job_opportunities (course_id, job_title) VALUES ($1, $2)`,
        [newCourse.course_id, job.job_title]
      );
    }

    await client.query('COMMIT');
    return newCourse;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

// => Whitelisted editable columns for the generic partial update.
// => admin_uuid is intentionally NOT in this list - it's a stable identifier,
// => never something a PATCH request should be able to change.
export const TESDA_COURSE_ALLOWED_COLUMNS = new Set([
  'title', 'description', 'accreditation_no', 'date_accredited',
  'expiration_date', 'sector_id', 'certification_id', 'amount', 'hours', 'cover_image_url', 'status',
]);

export async function updateTesdaCourse(adminUuid, fields) {
  const query = buildPartialUpdate({
    table: 'tesda_courses',
    idColumn: 'admin_uuid',
    idValue: adminUuid,
    fields,
    allowedColumns: TESDA_COURSE_ALLOWED_COLUMNS,
  });

  if (!query) return null;

  const result = await pool.query(query.text, query.values);
  return result.rows[0] || null;
}

// => Soft delete only - never hard delete a course, matches your standing rule
export async function softDeleteTesdaCourse(adminUuid) {
  const result = await pool.query(
    `UPDATE tesda_courses
     SET deleted_at = NOW(), updated_at = NOW()
     WHERE admin_uuid = $1 AND deleted_at IS NULL
     RETURNING course_id, admin_uuid`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => Deleted-courses list - the mirror image of findAllTesdaCourses, same
// => join shape, just flips the deleted_at filter
export async function findAllDeletedTesdaCourses() {
  const result = await pool.query(`
    SELECT tc.course_id, tc.admin_uuid, tc.title, tc.accreditation_no, tc.date_accredited,
           tc.expiration_date, tc.amount, tc.hours, tc.status, tc.sector_id,
           s.sector AS sector_name, tc.certification_id, nct.certification_type, tc.deleted_at
    FROM tesda_courses tc
    LEFT JOIN sectors s ON s.sector_id = tc.sector_id
    LEFT JOIN national_certification_types nct ON nct.certification_id = tc.certification_id
    WHERE tc.deleted_at IS NOT NULL
    ORDER BY tc.deleted_at DESC
  `);
  return result.rows;
}

// => Un-deletes a course - clears deleted_at, nothing else. Only matches rows
// => that are actually currently deleted (mirrors softDelete's guard).
export async function restoreTesdaCourse(adminUuid) {
  const result = await pool.query(
    `UPDATE tesda_courses
     SET deleted_at = NULL, updated_at = NOW()
     WHERE admin_uuid = $1 AND deleted_at IS NOT NULL
     RETURNING course_id, admin_uuid`,
    [adminUuid]
  );
  return result.rows[0] || null;
}

// => Add a single competency row after the course already exists (detail page
// => "+ Add Row"). Takes the course's admin_uuid (what the frontend has) and
// => resolves it to the internal course_id in the same query via a subquery -
// => avoids a separate round-trip just to look up the internal id first.
export async function updateCompetency(type, competencyId, { code, competency }) {
  const config = COMPETENCY_TABLES[type];
  if (!config) throw new Error('Invalid competency type');

  const result = await pool.query(
    // => course_id added to RETURNING so the service layer can log the
    // => correct entity_id without a separate lookup query
    `UPDATE ${config.table}
     SET code = $1, competency = $2
     WHERE ${config.idColumn} = $3
     RETURNING course_id, ${config.idColumn} AS id, code, competency`,
    [code, competency, competencyId]
  );
  return result.rows[0] || null;
}

export async function insertSingleCompetency(adminUuid, type, { code, competency }) {
  const config = COMPETENCY_TABLES[type];
  if (!config) throw new Error('Invalid competency type');

  const result = await pool.query(
    // => course_id added to RETURNING so the service layer can log without
    // => a separate findTesdaCourseByAdminUuid call
    `INSERT INTO ${config.table} (course_id, code, competency)
     SELECT course_id, $2, $3
     FROM tesda_courses
     WHERE admin_uuid = $1 AND deleted_at IS NULL
     RETURNING course_id, ${config.idColumn} AS id, code, competency`,
    [adminUuid, code, competency]
  );
  return result.rows[0] || null; // => null means the admin_uuid didn't match any course
}


export async function deleteCompetency(type, competencyId) {
  const config = COMPETENCY_TABLES[type];
  if (!config) throw new Error('Invalid competency type');

  const result = await pool.query(
    // => course_id added to RETURNING, same reasoning as updateCompetency above
    `DELETE FROM ${config.table} WHERE ${config.idColumn} = $1 RETURNING course_id, ${config.idColumn} AS id`,
    [competencyId]
  );
  return result.rows[0] || null;
}

// => Public link sub-resource removed (findPublicLinkByCourseId, isSlugTaken,
// => createPublicLink, updatePublicLink, PUBLIC_LINK_ALLOWED_COLUMNS) - the
// => publish gate was redundant with tesda_courses.status, which is what the
// => public site actually filters on. tesda_course_public_links table dropped in Neon.

// => Job opportunities sub-resource - same pattern as competencies: keyed by
// => the INTERNAL course_id for reads, resolved from admin_uuid via subquery
// => for inserts (per thesis scope: "potential career opportunities
// => available upon completion and assessment").

export async function findJobOpportunitiesByCourseId(courseId) {
  const result = await pool.query(
    `SELECT job_id AS id, job_title
     FROM tesda_job_opportunities WHERE course_id = $1 ORDER BY job_id ASC`,
    [courseId]
  );
  return result.rows;
}

export async function insertSingleJobOpportunity(adminUuid, jobTitle) {
  const result = await pool.query(
    // => course_id added to RETURNING, same reasoning as the competency inserts above
    `INSERT INTO tesda_job_opportunities (course_id, job_title)
     SELECT course_id, $2
     FROM tesda_courses
     WHERE admin_uuid = $1 AND deleted_at IS NULL
     RETURNING course_id, job_id AS id, job_title`,
    [adminUuid, jobTitle]
  );
  return result.rows[0] || null; // => null means the admin_uuid didn't match any course
}

export async function updateJobOpportunity(jobId, jobTitle) {
  const result = await pool.query(
    `UPDATE tesda_job_opportunities SET job_title = $1 WHERE job_id = $2 RETURNING course_id, job_id AS id, job_title`,
    [jobTitle, jobId]
  );
  return result.rows[0] || null;
}

export async function deleteJobOpportunity(jobId) {
  const result = await pool.query(
    `DELETE FROM tesda_job_opportunities WHERE job_id = $1 RETURNING course_id, job_id AS id`,
    [jobId]
  );
  return result.rows[0] || null;
}
